services:
  postgres:
    image: postgres:16-alpine
    container_name: desafio_inter_postgres
    environment:
      POSTGRES_DB: desafio_inter
      POSTGRES_USER: desafio_user
      POSTGRES_PASSWORD: desafio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U desafio_user -d desafio_inter"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: